# fly.toml app configuration file generated for tabatausa on 2023-08-22T20:59:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tabatausa"
primary_region = "scl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
